import { Product, User, Post, Story, Challenge, Category } from "@/types";
import courseAiMl from "@/assets/course-ai-ml.jpg";
import coursePython from "@/assets/course-python.jpg";
import bookHardcover from "@/assets/book-hardcover.jpg";
import studentKit from "@/assets/student-kit.jpg";
import promptLibrary from "@/assets/prompt-library.jpg";
import heroFashion from "@/assets/hero-fashion-1.jpg";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "AI & Machine Learning Masterclass",
    price: 49,
    originalPrice: 120,
    image: courseAiMl,
    brand: "Asikon Academy",
    rating: 4.9,
    reviews: 1842,
    isAuthentic: true,
    isTrending: true,
  },
  {
    id: "2",
    name: "Complete Python for Data Science (Course)",
    price: 39,
    image: coursePython,
    brand: "Asikon Academy",
    rating: 4.8,
    reviews: 2512,
    isAuthentic: true,
  },
  {
    id: "3",
    name: "Atomic Habits — Hardcover Book",
    price: 18,
    originalPrice: 25,
    image: bookHardcover,
    brand: "Bestseller",
    rating: 4.9,
    reviews: 9189,
    isAuthentic: true,
  },
  {
    id: "4",
    name: "Student Essentials Kit (Notebook + Stationery)",
    price: 22,
    image: studentKit,
    brand: "StudyGear",
    rating: 4.7,
    reviews: 467,
    isTrending: true,
  },
  {
    id: "5",
    name: "1000+ AI Prompt Library (Lifetime)",
    price: 29,
    originalPrice: 79,
    image: promptLibrary,
    brand: "Asikon AI",
    rating: 4.9,
    reviews: 3204,
    isAuthentic: true,
    isTrending: true,
  },
  {
    id: "6",
    name: "Web Development Bootcamp (HTML, CSS, JS, React)",
    price: 59,
    originalPrice: 199,
    image: coursePython,
    brand: "Asikon Academy",
    rating: 4.8,
    reviews: 4321,
    isAuthentic: true,
    isTrending: true,
  },
  {
    id: "7",
    name: "Deep Learning Specialization (Course)",
    price: 79,
    originalPrice: 199,
    image: courseAiMl,
    brand: "Asikon Academy",
    rating: 4.9,
    reviews: 2890,
    isAuthentic: true,
  },
  {
    id: "8",
    name: "Data Structures & Algorithms (Course)",
    price: 45,
    image: coursePython,
    brand: "Asikon Academy",
    rating: 4.7,
    reviews: 1567,
    isAuthentic: true,
  },
  {
    id: "9",
    name: "Deep Work — Hardcover Book",
    price: 20,
    originalPrice: 28,
    image: bookHardcover,
    brand: "Cal Newport",
    rating: 4.8,
    reviews: 6432,
    isAuthentic: true,
  },
  {
    id: "10",
    name: "Sapiens: A Brief History of Humankind",
    price: 24,
    originalPrice: 32,
    image: bookHardcover,
    brand: "Bestseller",
    rating: 4.9,
    reviews: 12453,
    isAuthentic: true,
    isTrending: true,
  },
  {
    id: "11",
    name: "Clean Code — Programmer's Handbook",
    price: 32,
    image: bookHardcover,
    brand: "Robert C. Martin",
    rating: 4.8,
    reviews: 5421,
    isAuthentic: true,
  },
  {
    id: "12",
    name: "AI Tutor Premium (1 Year Subscription)",
    price: 99,
    originalPrice: 240,
    image: promptLibrary,
    brand: "Asikon AI",
    rating: 4.9,
    reviews: 1834,
    isAuthentic: true,
    isTrending: true,
  },
  {
    id: "13",
    name: "ChatGPT Power Prompts (500+ Pack)",
    price: 19,
    originalPrice: 49,
    image: promptLibrary,
    brand: "Asikon AI",
    rating: 4.8,
    reviews: 2189,
    isAuthentic: true,
  },
  {
    id: "14",
    name: "Midjourney Prompt Library (Designers)",
    price: 25,
    image: promptLibrary,
    brand: "Asikon AI",
    rating: 4.7,
    reviews: 987,
    isAuthentic: true,
  },
  {
    id: "15",
    name: "Premium Study Planner & Notebook Set",
    price: 18,
    originalPrice: 30,
    image: studentKit,
    brand: "StudyGear",
    rating: 4.7,
    reviews: 723,
  },
  {
    id: "16",
    name: "Scientific Calculator + Geometry Kit",
    price: 28,
    image: studentKit,
    brand: "StudyGear",
    rating: 4.6,
    reviews: 612,
  },
  {
    id: "17",
    name: "IELTS Complete Prep Course + Books",
    price: 65,
    originalPrice: 150,
    image: bookHardcover,
    brand: "Asikon Academy",
    rating: 4.8,
    reviews: 3421,
    isAuthentic: true,
    isTrending: true,
  },
  {
    id: "18",
    name: "SAT Math Mastery (Course + Practice)",
    price: 49,
    image: coursePython,
    brand: "Asikon Academy",
    rating: 4.7,
    reviews: 1245,
    isAuthentic: true,
  },
  {
    id: "19",
    name: "Public Speaking Masterclass",
    price: 35,
    image: courseAiMl,
    brand: "Asikon Academy",
    rating: 4.8,
    reviews: 2103,
    isAuthentic: true,
  },
  {
    id: "20",
    name: "Productivity & Time Management Bundle",
    price: 27,
    originalPrice: 60,
    image: studentKit,
    brand: "Asikon Academy",
    rating: 4.6,
    reviews: 845,
  },
];

export const mockUser: User = {
  id: "1",
  name: "Sophia Vance",
  username: "sophia_v",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop",
  isVerified: true,
  followers: 12500,
  following: 210,
  sales: 156,
  trustScore: 98,
  coins: 2450,
  level: "Gold",
  bio: "CS student • AI enthusiast • Sharing my learning journey 📚✨",
};

export const mockStories: Story[] = [
  {
    id: "1",
    user: { ...mockUser, name: "Your Story" },
    thumbnail: mockUser.avatar,
    type: "image",
  },
  {
    id: "2",
    user: { ...mockUser, id: "2", name: "Asikon AI", username: "asikon_ai" },
    thumbnail: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=80&h=80&fit=crop",
    type: "image",
  },
  {
    id: "3",
    user: { ...mockUser, id: "3", name: "Study Daily", username: "studydaily" },
    thumbnail: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=80&h=80&fit=crop",
    type: "video",
  },
  {
    id: "4",
    user: { ...mockUser, id: "4", name: "Top Reads", username: "topreads" },
    thumbnail: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=80&h=80&fit=crop",
    type: "image",
  },
  {
    id: "5",
    user: { ...mockUser, id: "5", name: "Tutor Live", username: "tutorlive" },
    thumbnail: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=80&h=80&fit=crop",
    type: "video",
  },
];

export const mockPosts: Post[] = [
  {
    id: "1",
    user: {
      ...mockUser,
      name: "Sarah Learns",
      username: "sarah_learns",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop",
    },
    content: "Just finished the AI Masterclass on Asikon — the AI tutor cleared up every doubt I had! 🚀 #learning #ai",
    image: heroFashion,
    likes: 2400,
    comments: 45,
    shares: 12,
    timestamp: "2 hours ago",
    product: mockProducts[0],
  },
  {
    id: "2",
    user: mockUser,
    content: "My weekly study haul: new books + the Python course. Asikon recommended all of these for my goals 📚💫",
    image: bookHardcover,
    likes: 1850,
    comments: 89,
    shares: 34,
    timestamp: "5 hours ago",
    product: mockProducts[2],
  },
];

export const mockCategories: Category[] = [
  { id: "1", name: "All", icon: "✨" },
  { id: "2", name: "Courses", icon: "🎓" },
  { id: "3", name: "Books", icon: "📚" },
  { id: "4", name: "AI Tutor", icon: "🤖" },
  { id: "5", name: "Stationery", icon: "✏️" },
  { id: "6", name: "Gadgets", icon: "💻" },
];

export const mockChallenges: Challenge[] = [
  {
    id: "1",
    title: "Complete your first lesson",
    description: "Finish a lesson in any course",
    progress: 0,
    total: 1,
    reward: 50,
    icon: "🎓",
  },
  {
    id: "2",
    title: "Ask the AI Tutor 5 times",
    description: "Use the AI tutor to clear your doubts",
    progress: 3,
    total: 5,
    reward: 10,
    icon: "🤖",
  },
  {
    id: "3",
    title: "First Purchase",
    description: "Buy your first course or book",
    progress: 0,
    total: 1,
    reward: 100,
    icon: "🛍️",
  },
];
