// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tdbqeecjvitorxamzlok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkYnFlZWNqdml0b3J4YW16bG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1ODQyMjIsImV4cCI6MjA5NDE2MDIyMn0.4ddCCI1sPKyKYhpjdyV9NZ7tHWt9xTL56AdyWIQGlLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});